name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        go-version:
          - '1.21.x'
          - '1.22.x'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Check format
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Test
        run: go test -v
      - name: Benchmark
        run: go test -run=XXX -bench=. ./...
